//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package edu.njupt.zhb.xlistviewtest;

import android.content.Context;

public final class Model_
    extends Model
{

    private Context context_;

    private Model_(Context context) {
        context_ = context;
        init_();
    }

    public static Model_ getInstance_(Context context) {
        return new Model_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
